---
title: "map"
author: "Natalie Cochran and Jennifer Laws"
date: "December 4, 2015"
output:
  html_document:
    toc: yes
    number_sections: yes
---

## Create Map of Points

```{r}
# load packages
suppressWarnings(suppressPackageStartupMessages({
  library(leaflet)
  library(rgdal)
}))

# set paths
gdb = 'H:/Advanced_GIS/Lab3New/lab3/golf.gdb'

# read points from geodatabase
pts = readOGR(gdb, 'pts_tree', verbose=F)

# project points to geographic projection
pts_gcs = spTransform(pts, leaflet:::epsg4326)

# create map of points
leaflet() %>%
  addTiles() %>%
  addMarkers(data = pts_gcs) 
```


# Create map with popups

```{r}
leaflet() %>%
  addTiles() %>%
  addMarkers(data = pts_gcs, popup=~sprintf('id: %d', id)) 
```

# Create map with Stamen.Watercolor basemap

```{r}
leaflet() %>%  
  addProviderTiles('Stamen.Watercolor') %>%
  addMarkers(data = pts_gcs, popup=~sprintf('id: %d', id))
```

# Create map with Stamen.Toner basemap

```{r}
leaflet() %>%  
  addProviderTiles('Stamen.Toner') %>%
  addMarkers(data = pts_gcs, popup=~sprintf('id: %d', id))
```

# Create map with Thunderforest.TransportDark basemap

```{r}
leaflet() %>%  
  addProviderTiles('Thunderforest.TransportDark') %>%
  addMarkers(data = pts_gcs, popup=~sprintf('id: %d', id))

# Read points, lines and polygons from geodatabase
pts_gcs  = readOGR(gdb, 'pts_tree', verbose=F)    %>% spTransform(leaflet:::epsg4326)
lns_gcs  = readOGR(gdb, 'lns_cart', verbose=F)    %>% spTransform(leaflet:::epsg4326)
plys_gcs = readOGR(gdb, 'plys_bunker', verbose=F) %>% spTransform(leaflet:::epsg4326)
```

# Map with lines and polygons

```{r}
leaflet() %>%  
  addProviderTiles('Thunderforest.TransportDark') %>%
  addPolygons(data=plys_gcs, color = "yellow", stroke = FALSE) %>%  
  addPolylines(data=lns_gcs) %>%
  addMarkers(data=pts_gcs, popup=~sprintf('id: %d', id))

library(raster)

# Set path to your final chosen classified image
tif = 'H:/Advanced_GIS/Lab3New/lab3/images_rect/vid_sec279_5.tif'
  
# Read raster, presumably in Web Mercator
r = raster(tif, crs = leaflet:::epsg3857)

# Setup color palette
pal = colorFactor('Set3', values(r), na.color='transparent')
```

# Map with raster

```{r}
leaflet() %>%  
  addProviderTiles('Thunderforest.TransportDark') %>%
  addRasterImage(r, colors=pal, project=F, opacity = 0.7) %>%
  addLegend(pal=pal, values=values(r), title='Habitats')

library(rgdal)

gdb = 'H:/Advanced_GIS/Lab3New/lab3/golf.gdb'
dir = 'H:/Advanced_GIS/Lab5/lab5_online/adv-gis/data'

# Iterate through features in geodatabase
for (fc in ogrListLayers(gdb)){
  
  # print paths
  geo = sprintf('%s/%s.geojson', dir, fc)
  tmp = tempfile()
  cat(sprintf('gdb/fc: %s/%s\n  -> tmp: %s\n  -> geo: %s\n', gdb, fc, tmp, geo))
  
  # read in feature class
  sp = readOGR(gdb, fc)

  # output to geojson
  writeOGR(sp, dsn=tmp, layer='dummy', driver='GeoJSON')
  
  # move file
  file.rename(tmp, geo)
}
```
